development:
  adapter: postgresql
  database: cloud_dev
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  
test:
  adapter: postgresql
  database: cloud_dev
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  adapter: postgresql
  database: cloud
  username: postgres
  password: postgres
